In [116]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

In [117]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/car.csv'

In [118]:
data = pd.read_csv(file_url)
data

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage   engine  \
0     Individual       Manual           First Owner   23.4 kmpl  1248 CC   
1     Individual       Manual          Second Owner  21.14 kmpl  1498 CC   
2     Individual       Manual           Third Owner   17.7 kmpl  1497 CC   
3     Individual       Manual           First Owner   23.0 kmpl  1396 CC   
4     Individual       Manual           First Owner   16.1 kmpl  1298 CC   
...          ...          ...                   ...         ...      ...   
8123  Individual       Manual           First Owner   18.5 kmpl  1197 CC   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl  1493 CC   
8125  Individual       Manual           First Owner   19.3 kmpl  1248 CC   
8126  Individual       Manual           First Owner  23.57 kmpl  1396 CC   
8127  Individual       Manual           First Owner  23.57 kmpl  1396 CC   

       max_power                     torque  seats  
0         74 bhp             190Nm@ 2000rpm    5.0  
1     103.52 bhp        250Nm@ 1500-2500rpm    5.0  
2         78 bhp      12.7@ 2,700(kgm@ rpm)    5.0  
3         90 bhp   22.4 kgm at 1750-2750rpm    5.0  
4       88.2 bhp      11.5@ 4,500(kgm@ rpm)    5.0  
...          ...                        ...    ...  
8123   82.85 bhp           113.7Nm@ 4000rpm    5.0  
8124     110 bhp  24@ 1,900-2,750(kgm@ rpm)    5.0  
8125    73.9 bhp             190Nm@ 2000rpm    5.0  
8126      70 bhp        140Nm@ 1800-3000rpm    5.0  
8127      70 bhp        140Nm@ 1800-3000rpm    5.0  

[8128 rows x 13 columns]

In [119]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   mileage        7907 non-null   object 
 9   engine         7907 non-null   object 
 10  max_power      7913 non-null   object 
 11  torque         7906 non-null   object 
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB


In [120]:
data.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [121]:
data['engine'].str.split(expand=True)

0   1
0     1248  CC
1     1498  CC
2     1497  CC
3     1396  CC
4     1298  CC
...    ...  ..
8123  1197  CC
8124  1493  CC
8125  1248  CC
8126  1396  CC
8127  1396  CC

[8128 rows x 2 columns]

In [122]:
data[['engine','engine_unit']] = data['engine'].str.split(expand=True)

In [123]:
data['engine']= data['engine'].astype('float32')

In [124]:
data['engine_unit'].value_counts()

CC    7907
Name: engine_unit, dtype: int64

In [125]:
data.drop('engine_unit',axis=1,inplace=True)

In [131]:
data['max_power']

0           74
1       103.52
2           78
3           90
4         88.2
         ...  
8123     82.85
8124       110
8125      73.9
8126        70
8127        70
Name: max_power, Length: 8128, dtype: object

In [127]:
data[['max_power','max_power_unit']] = data['max_power'].str.split(expand=True)

In [132]:
data['max_power'] = data['max_power'].astype('float32')

ValueError: could not convert string to float: 'bhp'

In [133]:
data[data['max_power']=='bhp']

name  year  selling_price  km_driven fuel seller_type  \
4933  Maruti Omni CNG  2000          80000     100000  CNG  Individual   

     transmission         owner     mileage  engine max_power torque  seats  \
4933       Manual  Second Owner  10.9 km/kg   796.0       bhp    NaN    8.0   

     max_power_unit  
4933           None

In [134]:
def isFloat(val) :
    try :
        num = float(val)
        return num
    except ValueError:
        return np.NaN

In [135]:
data['max_power'] = data['max_power'].apply(isFloat)

In [136]:
data['max_power_unit'].unique()

array(['bhp', nan, None], dtype=object)

In [137]:
data.drop('max_power_unit',axis=1,inplace=True)

In [138]:
data[['mileage','mileage_unit']]  = data['mileage'].str.split(expand=True)

In [139]:
data['mileage'] = data['mileage'].astype('float32')

In [140]:
data['mileage_unit'].value_counts()

kmpl     7819
km/kg      88
Name: mileage_unit, dtype: int64

In [141]:
data['fuel'].unique()
# Petrol : 리터당 $80.43
# Diesel : 리터당 $73.56
# LPG : 킬로그램당 $40.85
# CNG : 킬로그램당 $44.23

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [142]:
def mile(x) :
    if x['fuel'] == 'Pertrol' :
        return x['mileage'] / 80.43
    elif x['fuel'] == 'Diesel':
        return x['mileage'] / 73.56
    elif x['fuel'] == 'LPG' :
        return x['mileage'] / 40.85
    else :
        return x['mileage'] / 44.23

In [143]:
data['mileage'] = data.apply(mile,axis=1)

In [144]:
data.drop('mileage_unit',axis=1,inplace=True)

In [145]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner   mileage  engine  max_power  \
0  Individual       Manual   First Owner  0.318108  1248.0      74.00   
1  Individual       Manual  Second Owner  0.287384  1498.0     103.52   
2  Individual       Manual   Third Owner  0.400181  1497.0      78.00   
3  Individual       Manual   First Owner  0.312670  1396.0      90.00   
4  Individual       Manual   First Owner  0.364006  1298.0      88.20   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [146]:
data['torque'] = data['torque'].str.upper()

In [147]:
def torque_unit(x) :
    if 'NM' in str(x) :
        return 'NM'
    elif 'KGM' in str(x) :
        return 'KGM'

In [148]:
data['torque_unit'] = data['torque'].apply(torque_unit)

In [149]:
data

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner   mileage  engine  \
0     Individual       Manual           First Owner  0.318108  1248.0   
1     Individual       Manual          Second Owner  0.287384  1498.0   
2     Individual       Manual           Third Owner  0.400181  1497.0   
3     Individual       Manual           First Owner  0.312670  1396.0   
4     Individual       Manual           First Owner  0.364006  1298.0   
...          ...          ...                   ...       ...     ...   
8123  Individual       Manual           First Owner  0.418268  1197.0   
8124  Individual       Manual  Fourth & Above Owner  0.228385  1493.0   
8125  Individual       Manual           First Owner  0.262371  1248.0   
8126  Individual       Manual           First Owner  0.320419  1396.0   
8127  Individual       Manual           First Owner  0.320419  1396.0   

      max_power                     torque  seats torque_unit  
0         74.00             190NM@ 2000RPM    5.0          NM  
1        103.52        250NM@ 1500-2500RPM    5.0          NM  
2         78.00      12.7@ 2,700(KGM@ RPM)    5.0         KGM  
3         90.00   22.4 KGM AT 1750-2750RPM    5.0         KGM  
4         88.20      11.5@ 4,500(KGM@ RPM)    5.0         KGM  
...         ...                        ...    ...         ...  
8123      82.85           113.7NM@ 4000RPM    5.0          NM  
8124     110.00  24@ 1,900-2,750(KGM@ RPM)    5.0         KGM  
8125      73.90             190NM@ 2000RPM    5.0          NM  
8126      70.00        140NM@ 1800-3000RPM    5.0          NM  
8127      70.00        140NM@ 1800-3000RPM    5.0          NM  

[8128 rows x 14 columns]

In [150]:
data['torque_unit'].value_counts()

NM     7390
KGM     504
Name: torque_unit, dtype: int64

In [151]:
data[data['torque_unit'].isnull()]['torque'].unique()

array([nan, '250@ 1250-5000RPM', '510@ 1600-2400', '110(11.2)@ 4800',
       '210 / 1900'], dtype=object)

In [152]:
data['torque_unit'] = data['torque_unit'].fillna('NM')

In [153]:
data['torque']

0                  190NM@ 2000RPM
1             250NM@ 1500-2500RPM
2           12.7@ 2,700(KGM@ RPM)
3        22.4 KGM AT 1750-2750RPM
4           11.5@ 4,500(KGM@ RPM)
                  ...            
8123             113.7NM@ 4000RPM
8124    24@ 1,900-2,750(KGM@ RPM)
8125               190NM@ 2000RPM
8126          140NM@ 1800-3000RPM
8127          140NM@ 1800-3000RPM
Name: torque, Length: 8128, dtype: object

In [154]:
def split_num(x) :
    x = str(x)
    for i,j in enumerate(x) :
        if j not in '0123456789.' :
            cut = i
            break
    return x[:cut]

In [155]:
data['torque'] = data['torque'].apply(split_num)

In [156]:
data

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner   mileage  engine  \
0     Individual       Manual           First Owner  0.318108  1248.0   
1     Individual       Manual          Second Owner  0.287384  1498.0   
2     Individual       Manual           Third Owner  0.400181  1497.0   
3     Individual       Manual           First Owner  0.312670  1396.0   
4     Individual       Manual           First Owner  0.364006  1298.0   
...          ...          ...                   ...       ...     ...   
8123  Individual       Manual           First Owner  0.418268  1197.0   
8124  Individual       Manual  Fourth & Above Owner  0.228385  1493.0   
8125  Individual       Manual           First Owner  0.262371  1248.0   
8126  Individual       Manual           First Owner  0.320419  1396.0   
8127  Individual       Manual           First Owner  0.320419  1396.0   

      max_power torque  seats torque_unit  
0         74.00    190    5.0          NM  
1        103.52    250    5.0          NM  
2         78.00   12.7    5.0         KGM  
3         90.00   22.4    5.0         KGM  
4         88.20   11.5    5.0         KGM  
...         ...    ...    ...         ...  
8123      82.85  113.7    5.0          NM  
8124     110.00     24    5.0         KGM  
8125      73.90    190    5.0          NM  
8126      70.00    140    5.0          NM  
8127      70.00    140    5.0          NM  

[8128 rows x 14 columns]

In [157]:
data['torque']=data['torque'].astype('float32')

ValueError: could not convert string to float: ''

In [158]:
data['torque']=data['torque'].replace('',np.NaN)

In [159]:
data['torque']=data['torque'].astype('float32')

In [160]:
data['torque'].head()

0    190.0
1    250.0
2     12.7
3     22.4
4     11.5
Name: torque, dtype: float32

In [161]:
def torque_tran(x) :
    if x['torque_unit'] == 'KGM' :
        return x['torque'] *9.8066
    else :
        return x['torque']


In [162]:
data['torque'] = data.apply(torque_tran,axis=1)

In [163]:
data.drop('torque_unit',axis=1,inplace=True)

In [164]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner   mileage  engine  max_power  \
0  Individual       Manual   First Owner  0.318108  1248.0      74.00   
1  Individual       Manual  Second Owner  0.287384  1498.0     103.52   
2  Individual       Manual   Third Owner  0.400181  1497.0      78.00   
3  Individual       Manual   First Owner  0.312670  1396.0      90.00   
4  Individual       Manual   First Owner  0.364006  1298.0      88.20   

       torque  seats  
0  190.000000    5.0  
1  250.000000    5.0  
2  124.543818    5.0  
3  219.667836    5.0  
4  112.775900    5.0

In [165]:
data['name'] = data['name'].str.split(expand=True)[0]

In [166]:
data['name'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [167]:
data['name'] = data['name'].replace('Land','Land Rover')

In [168]:
data.isnull().mean()
# 결측치가 약 2~3% 정도의 수준으로 보이고 있다.
# 결측치의 비율 2% 수준으로 높지 않기 때문에 과감하게 행을 모두 제거한다. 

name             0.000000
year             0.000000
selling_price    0.000000
km_driven        0.000000
fuel             0.000000
seller_type      0.000000
transmission     0.000000
owner            0.000000
mileage          0.027190
engine           0.027190
max_power        0.026575
torque           0.027313
seats            0.027190
dtype: float64

In [169]:
data.dropna(inplace=True)
len(data)

7906

In [170]:
data = pd.get_dummies(data,columns=['name','fuel','seller_type','transmission','owner'],drop_first=True)

In [171]:
data.head()

year  selling_price  km_driven   mileage  engine  max_power      torque  \
0  2014         450000     145500  0.318108  1248.0      74.00  190.000000   
1  2014         370000     120000  0.287384  1498.0     103.52  250.000000   
2  2006         158000     140000  0.400181  1497.0      78.00  124.543818   
3  2010         225000     127000  0.312670  1396.0      90.00  219.667836   
4  2007         130000     120000  0.364006  1298.0      88.20  112.775900   

   seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0    5.0           0          0  ...            1         0            0   
1    5.0           0          0  ...            1         0            0   
2    5.0           0          0  ...            0         0            1   
3    5.0           0          0  ...            1         0            0   
4    5.0           0          0  ...            0         0            1   

   seller_type_Individual  seller_type_Trustmark Dealer  transmission_Manual  \
0                       1                             0                    1   
1                       1                             0                    1   
2                       1                             0                    1   
3                       1                             0                    1   
4                       1                             0                    1   

   owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                           0                   0                     0   
1                           0                   1                     0   
2                           0                   0                     0   
3                           0                   0                     0   
4                           0                   0                     0   

   owner_Third Owner  
0                  0  
1                  0  
2                  1  
3                  0  
4                  0  

[5 rows x 48 columns]

In [172]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(data.drop('selling_price',axis=1),data['selling_price'],test_size=0.2,random_state=100)

In [173]:
from sklearn.ensemble import RandomForestRegressor

model  = RandomForestRegressor(random_state=100)
model.fit(X_train,y_train)
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

In [179]:
from sklearn.metrics import mean_squared_error

print(mean_squared_error(y_train,train_pred)**0.5)
print(mean_squared_error(y_test,test_pred)**0.5)

51290.81037316912
161837.75490834436


In [ ]:
from sklearn.model_selection import KFold

data

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage  engine  \
0     Individual       Manual           First Owner   23.4 kmpl  1248.0   
1     Individual       Manual          Second Owner  21.14 kmpl  1498.0   
2     Individual       Manual           Third Owner   17.7 kmpl  1497.0   
3     Individual       Manual           First Owner   23.0 kmpl  1396.0   
4     Individual       Manual           First Owner   16.1 kmpl  1298.0   
...          ...          ...                   ...         ...     ...   
8123  Individual       Manual           First Owner   18.5 kmpl  1197.0   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl  1493.0   
8125  Individual       Manual           First Owner   19.3 kmpl  1248.0   
8126  Individual       Manual           First Owner  23.57 kmpl  1396.0   
8127  Individual       Manual           First Owner  23.57 kmpl  1396.0   

     max_power                     torque  seats max_power_unit  
0           74             190Nm@ 2000rpm    5.0            bhp  
1       103.52        250Nm@ 1500-2500rpm    5.0            bhp  
2           78      12.7@ 2,700(kgm@ rpm)    5.0            bhp  
3           90   22.4 kgm at 1750-2750rpm    5.0            bhp  
4         88.2      11.5@ 4,500(kgm@ rpm)    5.0            bhp  
...        ...                        ...    ...            ...  
8123     82.85           113.7Nm@ 4000rpm    5.0            bhp  
8124       110  24@ 1,900-2,750(kgm@ rpm)    5.0            bhp  
8125      73.9             190Nm@ 2000rpm    5.0            bhp  
8126        70        140Nm@ 1800-3000rpm    5.0            bhp  
8127        70        140Nm@ 1800-3000rpm    5.0            bhp  

[8128 rows x 14 columns]

In [174]:
data.reset_index(drop=True,inplace=True)

In [175]:
data

year  selling_price  km_driven   mileage  engine  max_power      torque  \
0     2014         450000     145500  0.318108  1248.0      74.00  190.000000   
1     2014         370000     120000  0.287384  1498.0     103.52  250.000000   
2     2006         158000     140000  0.400181  1497.0      78.00  124.543818   
3     2010         225000     127000  0.312670  1396.0      90.00  219.667836   
4     2007         130000     120000  0.364006  1298.0      88.20  112.775900   
...    ...            ...        ...       ...     ...        ...         ...   
7901  2013         320000     110000  0.418268  1197.0      82.85  113.699997   
7902  2007         135000     119000  0.228385  1493.0     110.00  235.358400   
7903  2009         382000     120000  0.262371  1248.0      73.90  190.000000   
7904  2013         290000      25000  0.320419  1396.0      70.00  140.000000   
7905  2013         290000      25000  0.320419  1396.0      70.00  140.000000   

      seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0       5.0           0          0  ...            1         0            0   
1       5.0           0          0  ...            1         0            0   
2       5.0           0          0  ...            0         0            1   
3       5.0           0          0  ...            1         0            0   
4       5.0           0          0  ...            0         0            1   
...     ...         ...        ...  ...          ...       ...          ...   
7901    5.0           0          0  ...            0         0            1   
7902    5.0           0          0  ...            1         0            0   
7903    5.0           0          0  ...            1         0            0   
7904    5.0           0          0  ...            1         0            0   
7905    5.0           0          0  ...            1         0            0   

      seller_type_Individual  seller_type_Trustmark Dealer  \
0                          1                             0   
1                          1                             0   
2                          1                             0   
3                          1                             0   
4                          1                             0   
...                      ...                           ...   
7901                       1                             0   
7902                       1                             0   
7903                       1                             0   
7904                       1                             0   
7905                       1                             0   

      transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                       1                           0                   0   
1                       1                           0                   1   
2                       1                           0                   0   
3                       1                           0                   0   
4                       1                           0                   0   
...                   ...                         ...                 ...   
7901                    1                           0                   0   
7902                    1                           1                   0   
7903                    1                           0                   0   
7904                    1                           0                   0   
7905                    1                           0                   0   

      owner_Test Drive Car  owner_Third Owner  
0                        0                  0  
1                        0                  0  
2                        0                  1  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
7901                     0                  0  
7902                     0    

In [176]:
kf = KFold(n_splits=5)
X = data.drop('selling_price',axis=1)
y = data['selling_price']

In [177]:
for i,j in kf.split(X) :
    print(i,j)

[1582 1583 1584 ... 7903 7904 7905] [   0    1    2 ... 1579 1580 1581]
[   0    1    2 ... 7903 7904 7905] [1582 1583 1584 ... 3160 3161 3162]
[   0    1    2 ... 7903 7904 7905] [3163 3164 3165 ... 4741 4742 4743]
[   0    1    2 ... 7903 7904 7905] [4744 4745 4746 ... 6322 6323 6324]
[   0    1    2 ... 6322 6323 6324] [6325 6326 6327 ... 7903 7904 7905]


In [180]:
total_train_mse = []
total_test_mse = []
for train_idx , test_idx in kf.split(X) :
    X_train, X_test = X.loc[train_idx],X.loc[test_idx]
    y_train, y_test = y.loc[train_idx],y.loc[test_idx]


    model = RandomForestRegressor(random_state=100)
    model.fit(X_train,y_train)
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_mse = mean_squared_error(y_train,train_pred) ** 0.5
    test_mse = mean_squared_error(y_test,test_pred) ** 0.5

    total_train_mse.append(train_mse)
    total_test_mse.append(test_mse)


In [184]:
np.mean(total_train_mse)

56590.12704253825

In [183]:
np.mean(total_test_mse)

142304.0874950536

In [191]:
total_train_mse = []
total_test_mse = []

kf = KFold(n_splits=8)

for i,j in kf.split(X) :
    X_train,X_test = X.loc[i,:],X.loc[j,:]
    y_train,y_test = y.loc[i],y.loc[j]

    model = RandomForestRegressor(n_estimators=300,
                                  max_depth=50,
                                  min_samples_split=5,
                                  min_samples_leaf=1,
                                  n_jobs=-1,
                                  random_state=100)
    model.fit(X_train,y_train)
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_mse = mean_squared_error(y_train,train_pred) ** 0.5
    test_mse = mean_squared_error(y_test,test_pred) ** 0.5

    total_train_mse.append(train_mse)
    total_test_mse.append(test_mse)
    

In [192]:
np.mean(total_train_mse)

65284.09788025596

In [193]:
np.mean(total_test_mse)

137118.76729591948